name: Osseocare
favicon: null
layout_spectrum: 0.39436372043564916
typography_spectrum: 0.35108
title: REHAB
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#413f54'
    - '#000000'
    - '#808080'
    - '#cfa89c'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.6782355480827391
  saturation: 0.3035413168836385
  rhythmicContrast: 0.5531857626046985
purpose: []
